# Generated by Django 3.1.7 on 2021-03-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer_4',
        ),
    ]
