import {
  ADD_PROFILE_INFO_SUCCESS,
  ADD_PROFILE_INFO_FAIL,
  GET_PROFILE_INFO_SUCCESS,
  GET_PROFILE_INFO_FAIL,
  UPDATE_PROFILE_INFO_SUCCESS,
  GET_SINGLE_PROFILE_INFO_SUCCESS,
  GET_SINGLE_PROFILE_INFO_FAIL,
  UPDATE_PROFILE_INFO_FAIL,
  GET_SINGLE_USER_PROFILE_SUCCESS,
  GET_SINGLE_USER_PROFILE_FAIL,
  ADD_EDUCATION_SUCCESS,
  ADD_EDUCATION_FAIL,
  GET_EDUCATION_SUCCESS,
  GET_EDUCATION_FAIL,
  GET_SINGLE_EDUCATION_SUCCESS,
  GET_SINGLE_EDUCATION_FAIL,
  UPDATE_EDUCATION_SUCCESS,
  UPDATE_EDUCATION_FAIL,
  DELETE_EDUCATION_SUCCESS,
  DELETE_EDUCATION_FAIL,
  GET_USER_EDUCATION_SUCCESS,
  GET_USER_EDUCATION_FAIL,
  ADD_EXPERIENCE_SUCCESS,
  ADD_EXPERIENCE_FAIL,
  GET_EXPERIENCE_SUCCESS,
  GET_EXPERIENCE_FAIL,
  GET_SINGLE_EXPERIENCE_SUCCESS,
  GET_SINGLE_EXPERIENCE_FAIL,
  UPDATE_EXPERIENCE_SUCCESS,
  UPDATE_EXPERIENCE_FAIL,
  GET_USER_EXPERIENCE_SUCCESS,
  GET_USER_EXPERIENCE_FAIL,
  ADD_AVAILABILITY_SUCCESS,
  ADD_AVAILABILITY_FAIL,
  GET_AVAILABILITY_SUCCESS,
  GET_AVAILABILITY_FAIL,
  GET_SINGLE_AVAILABILITY_SUCCESS,
  GET_SINGLE_AVAILABILITY_FAIL,
  UPDATE_AVAILABILITY_SUCCESS,
  UPDATE_AVAILABILITY_FAIL,
  GET_USER_AVAILABILITY_SUCCESS,
  GET_USER_AVAILABILITY_FAIL,
  ADD_ROLE_SALARY_SUCCESS,
  ADD_ROLE_SALARY_FAIL,
  GET_ROLE_SALARY_SUCCESS,
  GET_ROLE_SALARY_FAIL,
  GET_SINGLE_ROLE_SALARY_SUCCESS,
  GET_SINGLE_ROLE_SALARY_FAIL,
  UPDATE_ROLE_SALARY_SUCCESS,
  UPDATE_ROLE_SALARY_FAIL,
  GET_USER_ROLE_SALARY_SUCCESS,
  GET_USER_ROLE_SALARY_FAIL,
  ADD_COMPANY_PROFILE_SUCCESS,
  ADD_COMPANY_PROFILE_FAIL,
  GET_COMPANY_PROFILE_SUCCESS,
  GET_COMPANY_PROFILE_FAIL,
  GET_SINGLE_COMPANY_PROFILE_SUCCESS,
  GET_SINGLE_COMPANY_PROFILE_FAIL,
  UPDATE_COMPANY_PROFILE_SUCCESS,
  UPDATE_COMPANY_PROFILE_FAIL,
  ADD_USER_SKILLS_SUCCESS,
  ADD_USER_SKILLS_FAIL,
  GET_USER_SKILLS_SUCCESS,
  GET_USER_SKILLS_FAIL,
  GET_USER_ALL_SKILLS_SUCCESS,
  GET_USER_ALL_SKILLS_FAIL,
  GET_SINGLE_USER_SKILLS_SUCCESS,
  GET_SINGLE_USER_SKILLS_FAIL,
  GET_USERS_SUCCESS,
  GET_USERS_FAIL,
  GET_SINGLE_USER_SUCCESS,
  GET_SINGLE_USER_FAIL,
} from '../actions/types'

const initialState = {
  userData: {},
  userExperience: {},
  userAvailability: {},
  userRole: {},
  userEducation: [],
  userEdu: {},
  companyProfile: {},
  userSkills: [],
  users: [],
  singleUser: {},
}

const profile = (state = initialState, action) => {
  const { payload, type } = action

  switch (type) {
    case GET_USERS_SUCCESS:
      return {
        ...state,
        users: payload,
      }
    case GET_SINGLE_USER_SUCCESS:
      return {
        ...state,
        singleUser: payload,
      }
    case ADD_PROFILE_INFO_SUCCESS:
    case GET_PROFILE_INFO_SUCCESS:
    case GET_SINGLE_PROFILE_INFO_SUCCESS:
    case UPDATE_PROFILE_INFO_SUCCESS:
    case GET_SINGLE_USER_PROFILE_SUCCESS:
      return {
        ...state,
        userData: payload,
      }
    case GET_USER_SKILLS_SUCCESS:
    case GET_USER_ALL_SKILLS_SUCCESS:
    case GET_SINGLE_USER_SKILLS_SUCCESS:
      return {
        ...state,
        userSkills: payload,
      }
    case ADD_USER_SKILLS_SUCCESS:
      return {
        ...state,
        userSkills: [payload, ...state.userSkills],
      }
    case ADD_EXPERIENCE_SUCCESS:
    case GET_EXPERIENCE_SUCCESS:
    case GET_SINGLE_EXPERIENCE_SUCCESS:
    case UPDATE_EXPERIENCE_SUCCESS:
    case GET_USER_EXPERIENCE_SUCCESS:
      return {
        ...state,
        userExperience: payload,
      }
    case ADD_AVAILABILITY_SUCCESS:
    case GET_AVAILABILITY_SUCCESS:
    case GET_SINGLE_AVAILABILITY_SUCCESS:
    case UPDATE_AVAILABILITY_SUCCESS:
    case GET_USER_AVAILABILITY_SUCCESS:
      return {
        ...state,
        userAvailability: payload,
      }
    case ADD_ROLE_SALARY_SUCCESS:
    case GET_ROLE_SALARY_SUCCESS:
    case GET_SINGLE_ROLE_SALARY_SUCCESS:
    case UPDATE_ROLE_SALARY_SUCCESS:
    case GET_USER_ROLE_SALARY_SUCCESS:
      return {
        ...state,
        userRole: payload,
      }
    case ADD_COMPANY_PROFILE_SUCCESS:
    case GET_COMPANY_PROFILE_SUCCESS:
    case GET_SINGLE_COMPANY_PROFILE_SUCCESS:
    case UPDATE_COMPANY_PROFILE_SUCCESS:
      return {
        ...state,
        companyProfile: payload,
      }
    case ADD_EDUCATION_SUCCESS:
      return {
        ...state,
        userEducation: [payload, ...state.userEducation],
      }
    case GET_EDUCATION_SUCCESS:
    case GET_USER_EDUCATION_SUCCESS:
      return {
        ...state,
        userEducation: payload,
      }
    case GET_SINGLE_EDUCATION_SUCCESS:
    case UPDATE_EDUCATION_SUCCESS:
    case DELETE_EDUCATION_SUCCESS:
      return {
        ...state,
        userEdu: payload,
      }
    case ADD_PROFILE_INFO_FAIL:
    case GET_PROFILE_INFO_FAIL:
    case GET_SINGLE_PROFILE_INFO_FAIL:
    case UPDATE_PROFILE_INFO_FAIL:
    case GET_SINGLE_USER_PROFILE_FAIL:
    case ADD_EXPERIENCE_FAIL:
    case GET_EXPERIENCE_FAIL:
    case GET_SINGLE_EXPERIENCE_FAIL:
    case UPDATE_EXPERIENCE_FAIL:
    case GET_USER_EXPERIENCE_FAIL:
    case ADD_AVAILABILITY_FAIL:
    case GET_AVAILABILITY_FAIL:
    case GET_SINGLE_AVAILABILITY_FAIL:
    case UPDATE_AVAILABILITY_FAIL:
    case GET_USER_AVAILABILITY_FAIL:
    case ADD_ROLE_SALARY_FAIL:
    case GET_ROLE_SALARY_FAIL:
    case GET_SINGLE_ROLE_SALARY_FAIL:
    case UPDATE_ROLE_SALARY_FAIL:
    case GET_USER_ROLE_SALARY_FAIL:
    case ADD_EDUCATION_FAIL:
    case GET_EDUCATION_FAIL:
    case GET_SINGLE_EDUCATION_FAIL:
    case UPDATE_EDUCATION_FAIL:
    case DELETE_EDUCATION_FAIL:
    case GET_USER_EDUCATION_FAIL:
    case ADD_COMPANY_PROFILE_FAIL:
    case GET_COMPANY_PROFILE_FAIL:
    case GET_SINGLE_COMPANY_PROFILE_FAIL:
    case UPDATE_COMPANY_PROFILE_FAIL:
    case ADD_USER_SKILLS_FAIL:
    case GET_USER_SKILLS_FAIL:
    case GET_USER_ALL_SKILLS_FAIL:
    case GET_SINGLE_USER_SKILLS_FAIL:
    case GET_USERS_FAIL:
    case GET_SINGLE_USER_FAIL:
      return {
        ...state,
      }
    default:
      return state
  }
}

export default profile
