/* AUTHENTICATION ALERT NOTIFICATIONS */
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

/* ACCOUNT ACTIVATION */
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'

/* UPDATE PASSWORD */
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

/* RESET PASSWORD */
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL'
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL'
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS'

/* USER LOADING */
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'

/* USERS */
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL'

/* USER PROFILE INFORMATION */
export const ADD_PROFILE_INFO_SUCCESS = 'ADD_PROFILE_INFO_SUCCESS'
export const ADD_PROFILE_INFO_FAIL = 'ADD_PROFILE_INFO_FAIL'
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS'
export const GET_PROFILE_INFO_FAIL = 'GET_PROFILE_INFO_FAIL'
export const GET_SINGLE_PROFILE_INFO_SUCCESS = 'GET_SINGLE_PROFILE_INFO_SUCCESS'
export const GET_SINGLE_PROFILE_INFO_FAIL = 'GET_SINGLE_PROFILE_INFO_FAIL'
export const UPDATE_PROFILE_INFO_SUCCESS = 'UPDATE_PROFILE_INFO_SUCCESS'
export const UPDATE_PROFILE_INFO_FAIL = 'UPDATE_PROFILE_INFO_FAIL'
export const GET_SINGLE_USER_PROFILE_SUCCESS = 'GET_SINGLE_USER_PROFILE_SUCCESS'
export const GET_SINGLE_USER_PROFILE_FAIL = 'GET_SINGLE_USER_PROFILE_FAIL'

/* USER SKILLS */
export const ADD_USER_SKILLS_SUCCESS = 'ADD_USER_SKILLS_SUCCESS'
export const ADD_USER_SKILLS_FAIL = 'ADD_USER_SKILLS_FAIL'
export const GET_USER_ALL_SKILLS_SUCCESS = 'GET_USER_ALL_SKILLS_SUCCESS'
export const GET_USER_ALL_SKILLS_FAIL = 'GET_USER_ALL_SKILLS_FAIL'
export const GET_USER_SKILLS_SUCCESS = 'GET_USER_SKILLS_SUCCESS'
export const GET_USER_SKILLS_FAIL = 'GET_USER_SKILLS_FAIL'
export const GET_SINGLE_USER_SKILLS_SUCCESS = 'GET_SINGLE_USER_SKILLS_SUCCESS'
export const GET_SINGLE_USER_SKILLS_FAIL = 'GET_SINGLE_USER_SKILLS_FAIL'
export const GET_SINGLE_JOB_SKILLS_SUCCESS = 'GET_SINGLE_JOB_SKILLS_SUCCESS'
export const GET_SINGLE_JOB_SKILLS_FAIL = 'GET_SINGLE_JOB_SKILLS_FAIL'

/* USER EDUCATION INFORMATION */
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS'
export const ADD_EDUCATION_FAIL = 'ADD_EDUCATION_FAIL'
export const GET_EDUCATION_SUCCESS = 'GET_EDUCATION_SUCCESS'
export const GET_EDUCATION_FAIL = 'GET_EDUCATION_FAIL'
export const GET_SINGLE_EDUCATION_SUCCESS = 'GET_SINGLE_EDUCATION_SUCCESS'
export const GET_SINGLE_EDUCATION_FAIL = 'GET_SINGLE_EDUCATION_FAIL'
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS'
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL'
export const UPDATE_EDUCATION_SUCCESS = 'UPDATE_EDUCATION_SUCCESS'
export const UPDATE_EDUCATION_FAIL = 'UPDATE_EDUCATION_FAIL'
export const GET_USER_EDUCATION_SUCCESS = 'GET_USER_EDUCATION_SUCCESS'
export const GET_USER_EDUCATION_FAIL = 'GET_USER_EDUCATION_FAIL'

/* USER EXPERIENCE INFORMATION */
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS'
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL'
export const GET_EXPERIENCE_SUCCESS = 'GET_EXPERIENCE_SUCCESS'
export const GET_EXPERIENCE_FAIL = 'GET_EXPERIENCE_FAIL'
export const GET_SINGLE_EXPERIENCE_SUCCESS = 'GET_SINGLE_EXPERIENCE_SUCCESS'
export const GET_SINGLE_EXPERIENCE_FAIL = 'GET_SINGLE_EXPERIENCE_FAIL'
export const UPDATE_EXPERIENCE_SUCCESS = 'UPDATE_EXPERIENCE_SUCCESS'
export const UPDATE_EXPERIENCE_FAIL = 'UPDATE_EXPERIENCE_FAIL'
export const GET_USER_EXPERIENCE_SUCCESS = 'GET_USER_EXPERIENCE_SUCCESS'
export const GET_USER_EXPERIENCE_FAIL = 'GET_USER_EXPERIENCE_FAIL'

/* USER AVAILABILITY INFORMATION */
export const ADD_AVAILABILITY_SUCCESS = 'ADD_AVAILABILITY_SUCCESS'
export const ADD_AVAILABILITY_FAIL = 'ADD_AVAILABILITY_FAIL'
export const GET_AVAILABILITY_SUCCESS = 'GET_AVAILABILITY_SUCCESS'
export const GET_AVAILABILITY_FAIL = 'GET_AVAILABILITY_FAIL'
export const GET_SINGLE_AVAILABILITY_SUCCESS = 'GET_SINGLE_AVAILABILITY_SUCCESS'
export const GET_SINGLE_AVAILABILITY_FAIL = 'GET_SINGLE_AVAILABILITY_FAIL'
export const UPDATE_AVAILABILITY_SUCCESS = 'UPDATE_AVAILABILITY_SUCCESS'
export const UPDATE_AVAILABILITY_FAIL = 'UPDATE_AVAILABILITY_FAIL'
export const GET_USER_AVAILABILITY_SUCCESS = 'GET_USER_AVAILABILITY_SUCCESS'
export const GET_USER_AVAILABILITY_FAIL = 'GET_USER_AVAILABILITY_FAIL'

/* USER ROLE AND SALARY INFORMATION */
export const ADD_ROLE_SALARY_SUCCESS = 'ADD_ROLE_SALARY_SUCCESS'
export const ADD_ROLE_SALARY_FAIL = 'ADD_ROLE_SALARY_FAIL'
export const GET_ROLE_SALARY_SUCCESS = 'GET_ROLE_SALARY_SUCCESS'
export const GET_ROLE_SALARY_FAIL = 'GET_ROLE_SALARY_FAIL'
export const GET_SINGLE_ROLE_SALARY_SUCCESS = 'GET_SINGLE_ROLE_SALARY_SUCCESS'
export const GET_SINGLE_ROLE_SALARY_FAIL = 'GET_SINGLE_ROLE_SALARY_FAIL'
export const UPDATE_ROLE_SALARY_SUCCESS = 'UPDATE_ROLE_SALARY_SUCCESS'
export const UPDATE_ROLE_SALARY_FAIL = 'UPDATE_ROLE_SALARY_FAIL'
export const GET_USER_ROLE_SALARY_SUCCESS = 'GET_USER_ROLE_SALARY_SUCCESS'
export const GET_USER_ROLE_SALARY_FAIL = 'GET_USER_ROLE_SALARY_FAIL'

/* COMPANY PROFILE INFORMATION */
export const ADD_COMPANY_PROFILE_SUCCESS = 'ADD_COMPANY_PROFILE_SUCCESS'
export const ADD_COMPANY_PROFILE_FAIL = 'ADD_COMPANY_PROFILE_FAIL'
export const GET_COMPANY_PROFILE_SUCCESS = 'GET_COMPANY_PROFILE_SUCCESS'
export const GET_COMPANY_PROFILE_FAIL = 'GET_COMPANY_PROFILE_FAIL'
export const GET_SINGLE_COMPANY_PROFILE_SUCCESS =
  'GET_SINGLE_COMPANY_PROFILE_SUCCESS'
export const GET_SINGLE_COMPANY_PROFILE_FAIL = 'GET_SINGLE_COMPANY_PROFILE_FAIL'
export const UPDATE_COMPANY_PROFILE_SUCCESS = 'UPDATE_COMPANY_PROFILE_SUCCESS'
export const UPDATE_COMPANY_PROFILE_FAIL = 'UPDATE_COMPANY_PROFILE_FAIL'

/* JOBS */
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS'
export const ADD_JOB_FAIL = 'ADD_JOB_FAIL'
export const ADD_JOB_SKILLS_SUCCESS = 'ADD_JOB_SKILLS_SUCCESS'
export const ADD_JOB_SKILLS_FAIL = 'ADD_JOB_SKILLS_FAIL'
export const GET_LAST_ADDED_JOB_SUCCESS = 'GET_LAST_ADDED_JOB_SUCCESS'
export const GET_LAST_ADDED_JOB_FAIL = 'GET_LAST_ADDED_JOB_FAIL'
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS'
export const GET_ALL_JOB_FAIL = 'GET_ALL_JOB_FAIL'
export const GET_SINGLE_JOB_SUCCESS = 'GET_SINGLE_JOB_SUCCESS'
export const GET_SINGLE_JOB_FAIL = 'GET_SINGLE_JOB_FAIL'
export const GET_ALL_SKILLS_SUCCESS = 'GET_ALL_SKILLS_SUCCESS'
export const GET_ALL_SKILLS_FAIL = 'GET_ALL_SKILLS_FAIL'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL'

/* ASSESSMENTS */
export const GET_FIRST_QUESTION_SUCCESS = 'GET_FIRST_QUESTION_SUCCESS'
export const GET_FIRST_QUESTION_FAIL = 'GET_FIRST_QUESTION_FAIL'
export const GET_ANSWERS_SUCCESS = 'GET_ANSWERS_SUCCESS'
export const GET_ANSWERS_FAIL = 'GET_ANSWERS_FAIL'
export const GET_NEXT_QUESTION_SUCCESS = 'GET_NEXT_QUESTION_SUCCESS'
export const GET_NEXT_QUESTION_FAIL = 'GET_NEXT_QUESTION_FAIL'
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS'
export const SUBMIT_ANSWER_FAIL = 'SUBMIT_ANSWER_FAIL'
export const GET_USER_ANSWERS_SUCCESS = 'GET_USER_ANSWERS_SUCCESS'
export const GET_USER_ANSWERS_FAIL = 'GET_USER_ANSWERS_FAIL'
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS'
export const GET_ALL_QUESTIONS_FAIL = 'GET_ALL_QUESTIONS_FAIL'
