from django.urls import path
from .views import (UsersList,
                    RecommendUsersList,
                    ProfileList,
                    ProfileDetail,
                    ProfileUser,
                    AvailabilityList,
                    AvailabilityDetail,
                    AvailabilityUser,
                    EducationList,
                    EducationDetail,
                    EducationUser,
                    ExperienceList,
                    ExperienceDetail,
                    ExperienceUser,
                    RoleSalaryList,
                    RoleSalaryDetail,
                    RoleSalaryUser,
                    CompanyProfileList,
                    CompanyProfileDetail,
                    UserSkillsList,
                    UsersSkills,
                    UserSingle)

urlpatterns = [
    path('list', UsersList.as_view()),
    path('recommend/list', RecommendUsersList.as_view()),
    path('list/<int:pk>', UserSingle.as_view()),
    path('profile', ProfileList.as_view()),
    path('profile/<int:pk>', ProfileDetail.as_view()),
    path('profile/<int:pk>/user', ProfileUser.as_view()),
    path('availability', AvailabilityList.as_view()),
    path('availability/<int:pk>', AvailabilityDetail.as_view()),
    path('availability/<int:pk>/user', AvailabilityUser.as_view()),
    path('education', EducationList.as_view()),
    path('education/<int:pk>', EducationDetail.as_view()),
    path('education/<int:pk>/user', EducationUser.as_view()),
    path('experience', ExperienceList.as_view()),
    path('experience/<int:pk>', ExperienceDetail.as_view()),
    path('experience/<int:pk>/user', ExperienceUser.as_view()),
    path('role', RoleSalaryList.as_view()),
    path('role/<int:pk>', RoleSalaryDetail.as_view()),
    path('role/<int:pk>/user', RoleSalaryUser.as_view()),
    path('company_profile', CompanyProfileList.as_view()),
    path('company_profile/<int:pk>', CompanyProfileDetail.as_view()),
    path('user_skills', UserSkillsList.as_view()),
    path('user_skills/list', UsersSkills.as_view()),
    path('user_skills/list/<int:pk>', UsersSkills.as_view()),
]
